package com.co.iatech.crm.sugarmovil.core;

public enum Info {
	URL_INFO,CUENTA_ACTUAL, CONTACTO_ACTUAL, OPORTUNIDAD_SELECCIONADA, ID_LLAMADA, 
	ID_LLAMADA_ACTUAL, USUARIO, ID_PRODUCTO, ID_TAREA, TAREA_ACTUAL
}
